name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '4 2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        mkdir -p instances/fedi.simonwillison.net
        mkdir -p instances/vis.social
        mkdir -p instances/mastodon.social
        curl https://fedi.simonwillison.net/api/v1/instance/peers | jq . > instances/fedi.simonwillison.net/peers.json
        curl https://vis.social/api/v1/instance/peers  | jq . > instances/vis.social/peers.json
        curl https://mastodon.social/api/v1/instance/peers | jq . > instances/mastodon.social/peers.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
